### ISSUE TITLE
Test "anon_relative: test for relative module ids in anonymous modules" doesn't test exactly what it says

### ISSUE THREAD

**Issue by briancray** [amdjs/amdjs-tests#13]
The test requires that config.paths be configurable in order for it to pass. However, loaders can support relative module ids for anonymous modules without the paths object.

config.paths support should be tested for support separately from anonymous tests.

**Comment by thecodedrift** [comment]
Adding some notes around the test, what it should probably be testing, and how we might be able to reconcile this.

First, I think we should be able to restructure this test to specifically test for relative dependencies

```
Directory
|-anon_relative/
  |-impl/
    |-array.js
    |-util.js
  |- util.js

Dependency Chain
_test
  \=> impl/array
        \=> ./util (test what util was called)
        \=> util (test what util was called)
```

Second, the original test focuses on URL rewriting, which should be folded under config.paths IMO.

**Comment by briancray** [comment]
That makes more sense to me than the current test alone.

**Comment by jrburke** [comment]
@Jakobo I am open to that change too. If you are up for it, feel free to do the change. I likely will not get to it for a bit due to other priorities.

**Comment by thecodedrift** [comment]
Added the pull request. Other module libraries may want to opt in to configPaths if they support it. (I never realized Inject did technically, it's just under a different method name)
