### ISSUE TITLE
commentRegExp problem

### ISSUE THREAD

**Issue by guanyuxin** [amdjs/amdjs-tests#4]
commentRegExp = /(\/*([\s\S]_?)\_\/|([^:]|^)\/\/(._)$)/mg
this will not work right in conditions like
a="...foo.../_...foo..."
or in
href="http://foo.foo"

**Comment by jrburke** [comment]
This is an implementation detail specific to requirejs. Feel free to open a ticket at the [requirejs issues page](https://github.com/jrburke/requirejs/issues).

But as further information, that regexp is only used to remove comments when doing a Function.prototype.toString() on the factory function and scanning for require('') calls in this form:

```
define(function(require) {
    // the require in the comment below should not be found as a dependency
    // var a = require('a');

    // but this one should be:
    var b = require('b');
});
```
